api/urls.py
from django.urls import path

from api.views import ProductListAPIView, ProductRetrieveAPIView

app_name = 'api'

urlpatterns = [
    path('products/', ProductListAPIView.as_view()),
    path('products/<int:pk>/', ProductRetrieveAPIView.as_view()),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += i18n_patterns(
    path('accounts/', include('auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls', namespace='posts')),
    path('api/', include('api.urls', namespace='api')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('profile/', include('users.urls', namespace='profile')),
    path('', include('pages.urls', namespace='pages')),
    path('products/', include('products.urls', namespace='products')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from pages.views import ContactCreateView, AboutTemplateView, HomeTemplateView

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('', HomeTemplateView.as_view(), name='home'),
]

posts/urls.py
from django.urls import path

from posts.views import PostsListView, PostDetailView, CommentCreateView

app_name = 'posts'

urlpatterns = [
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
    path('', PostsListView.as_view(), name='list'),
]

products/urls.py
from django.urls import path

from products.views import ProductsListView, ProductDetailView, WishListListView, add_wishlist, add_to_cart

app_name = 'products'

urlpatterns = [
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('wishlist/', WishListListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_wishlist, name='add-wishlist'),
    path('cart/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('', ProductsListView.as_view(), name='list'),
]

templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {% block extra_css %}{% endblock %}
</head>

<body>

<div id="preloader">
    <div class="loader"></div>
</div>

{% include 'layouts/header.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}




<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

templates/layouts/footer.html
{% load static %}
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                    </div>
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivery</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>NewLetter</h6>
                    <div class="footer__newslatter">
                        <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                        <form action="#">
                            <input type="text" placeholder="Your email">
                            <button type="submit"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

templates/layouts/header.html
{% block extra_css %}
    <style>
        .search {
            position: absolute;
            top: 80%;
            left: 60%;
            -webkit-transform: translateX(-50%) translateY(-50%);
            transform: translateX(-100%) translateY(-103%);
        }

        .search * {
            outline: none;
            box-sizing: border-box;
        }

        .search__wrapper {
            position: relative;
        }

        .search__field {
            width: 50px;
            height: 50px;
            color: transparent;
            font-family: Lato, sans-serif;
            font-size: 1.25em;
            padding: 0.35em 50px 0.35em 0;
            border: 1px solid transparent;
            border-radius: 0;
            cursor: pointer;
            transition: all 0.3s ease-in-out;
        }

        .search__field:focus {
            position: relative;
        {#border-bottom-color: #ccc;#} width: 14vw;
            color: #2b2b2b;
            cursor: default;

        }

        .search__field:focus ~ .search__icon {
            background-color: transparent;
            cursor: pointer;
            pointer-events: auto;
        }

        .search__icon {
            position: absolute;
            top: 1px;
            right: 2vh;
            width: 50px;
            height: 50px;
            font-size: 1.35em;
            text-align: center;
            border-color: transparent;
            border-radius: 50%;
            pointer-events: none;
            display: inline-block;
            transition: background-color 0.2s ease-in-out;
            background-color: white;
        }

        .search__field::-webkit-input-placeholder {
            position: relative;
            top: 0;
            left: 0;
            transition-property: top, color;
            transition-duration: .1s;
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;

        }

        .search__field:-moz-placeholder {
            position: relative;
            top: 0;
            left: 0;
            transition-property: top, color;
            transition-duration: .1s;
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;

        }

        .search__field::-moz-placeholder {
            position: relative;
            top: 0;
            left: 0;
            transition-property: top, color;
            transition-duration: .1s;
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;

        }

        .search__field:-ms-input-placeholder {
            position: relative;
            top: 0;
            left: 0;
            transition-property: top, color;
            transition-duration: .1s;
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;

        }

        .search__field::-webkit-input-placeholder[style*=hidden] {
            color: #83b0c1;
            font-size: .50em;
            font-weight: normal;
            top: -20px;
            opacity: 1;
            visibility: visible !important;
        }

        .search__field:-moz-placeholder[style*=hidden] {
            color: #83b0c1;
            font-size: .50em;
            font-weight: normal;
            top: -20px;
            opacity: 1;
            visibility: visible !important;
        }

        .search__field::-moz-placeholder[style*=hidden] {
            color: #83b0c1;
            font-size: .50em;
            font-weight: normal;
            top: -20px;
            opacity: 1;
            visibility: visible !important;
        }

        .search__field:-ms-input-placeholder[style*=hidden] {
            color: #83b0c1;
            font-size: .50em;
            font-weight: normal;
            top: -20px;
            opacity: 1;
            visibility: visible !important;
        }

    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
{% endblock %}

{% load static %}

{% load i18n %}

{% load my_tags %}

<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="#">
                {% blocktrans %}Sign in{% endblocktrans %}
            </a>
            <a href="#">
                {% trans 'FAQs' %}
            </a>
        </div>
        <div class="offcanvas__top__hover">
            {% get_current_language as lang %}
            <span>{{ lang }}<i class="arrow_carrot-down"></i></span>
            <ul>
                {% get_available_languages as all_langs %}
                {% for l in all_langs %}
                    {% if l.0 != lang %}
                        <li>
                            <a style="color: #111; text-decoration: none" href="{% get_lang_url request l.0 %}"></a>
                        </li>
                    {% endif %}

                {% endfor %}

            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
    </div>
</div>
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                           {% if request.user.is_authenticated %}
                             <a href="{% url 'profile:home' %}">{% trans 'Profile' %}</a>
                             <a href="">{% trans 'History' %}</a>
                             <a href="{% url 'auth_logout' %}">{% trans 'Log out' %}</a>
                            {% else %}
                            <a href="{% url 'auth_login' %}">{% trans 'Sign in' %}</a>
                            {% endif %}
                        </div>
                        <div class="header__top__hover">
                            {% get_current_language as lang %}
                            <span>{{ lang }}<i class="arrow_carrot-down"></i></span>
                            <ul>
                                {% get_available_languages as all_langs %}
                                {% for l in all_langs %}
                                    {% if l.0 != lang %}
                                        <li>
                                            <a style="color: #111; text-decoration: none"
                                               href="{% get_lang_url request l.0 %}">{{ l.0|upper }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>{% url 'pages:home' as home_url %}
                        <li class="{% if request.path == home_url %} active {% endif %}">
                            <a href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                        </li>
                        <li class="{% if '/products/' in request.path %} active {% endif %}"><a
                                href="{% url 'products:list' %}">{% trans 'Products' %}</a>
                        </li>
                        <li class="{% if '/blog/' in request.path %} active {% endif %}"><a
                                href="{% url 'posts:list' %}">{% trans 'Blog' %}</a></li>
                        <li class="{% if '/about/' in request.path %} active {% endif %}"><a
                                href="{% url 'pages:about' %}">{% trans 'About' %}</a></li>
                        <li class="{% if '/contact/' in request.path %} active {% endif %}"><a
                                href="{% url 'pages:contact' %}">{% trans 'Contact' %}</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <form action="{% url 'products:list' %}" class="search">
                        <div class="search__wrapper">
                            <input type="text" name="q" placeholder="Search..." class="search__field">
                            <button type="submit" class="fa fa-search search__icon"></button>
                        </div>
                    </form>
                    <a href="/"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="{% url 'products:wishlist' %}">
                        <img src="{% static 'img/icon/cart.png' %}" alt="">
                        <span>{% cart_count request %}</span></a>
                    <div class="price">{% cart_price request %}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>

templates/layouts/product_block.html
{% load static %}
{% load my_tags %}

<div class="product__item sale">
    <div class="product__item__pic set-bg"
         data-setbg="{{ products.image.url }}">
        {% if products.is_discount %}
            <span class="label">Sale</span>
        {% endif %}
        {% if product.is_new %}
            <span class="label {% if product.is_discount %}mt-4{% endif %}">New</span>
        {% endif %}
        <ul class="product__hover">
            <li>
                <a href="{% url 'products:add-wishlist' pk=products.pk %}?next={{ request.path }}?{{ request.GET.urlencode }}">
                    {% if products|in_wishlist:request %}
                        <img src="{% static 'img/icon/heartr.png' %}" alt="">
                    {% else %}
                        <img src="{% static 'img/icon/heart.png' %}" alt="">
                    {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'products:detail' pk=products.pk %}">
                    <img src="{% static 'img/icon/search.png' %}" alt="">
                </a>
            </li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ products.title }}</h6>
        <a href="{% url 'products:add-to-cart' pk=products.pk %}?next={{ request.path }}?{{ request.GET.urlencode }}"
           class="add-cart">
            {% if products|in_cart:request %}
                - Remove From Cart
            {% else %}
                + Add To Cart
            {% endif %}
        </a>
        <div class="rating">
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>${{ products.real_price }}
            {% if products.is_discount %}
                <strike class="small">{{ products.price }}</strike>
            {% endif %}
        </h5>
        <div class="product__color__select">
            <label for="pc-4">
                <input type="radio" id="pc-4">
            </label>
            <label class="active black" for="pc-5">
                <input type="radio" id="pc-5">
            </label>
            <label class="grey" for="pc-6">
                <input type="radio" id="pc-6">
            </label>
        </div>
    </div>
</div>